### PR TITLE
Update hit.ts

### PR DESCRIPTION
**Pull request by Ambryal**
fix: stun while counter is now correctly displayed

### CODE REVIEW

**Comment by Ambryal** [comment]
I'm sorry for the mess I have a better implementation on my side but I would have to push some other things for it to work.
This is a quick fix that should prevent ppl from posting in bugs because they don't see the stun.

**Comment by Ambryal** [comment]
I know there is a :drop for the death but this takes too long it looks weird

**Review by Zenoo — CHANGES_REQUESTED** [review]
This implementation would prevent the attacker from going back, I don't think this is the correct solution.
I think a better solution for stuns would be to make them slide the brute backwards with a stagger, creating space between the fighters

**Comment by Ambryal** [comment]
This implementation only let the stun animation time to display.

I don't believe there is better options and I don't believe this is an issue. Stunned fighters don't go back until woke up,  that's just logic, and making them slide for no reason is just so cheap...

I believe there is no issue after this fix as people will understand what's happending. People were just not seeing the brute was stunned.

**Comment by Zenoo** [comment]
No, this fix does create an issue, as it will act out like this:

- Brute A hits brute B
- Brute B gets stunned
- Brute A waits for Brute B to show the stun
- Brute A goes back
- next steps

The easiest solution would instead be:

- Brute A hits brute B
- Brute B gets stunned
- Brute A goes back
- Brute A waits for Brute B to show the stun
- next steps

Going back without waiting for the stun is important, as going back shouldn't depend on the opponent being stunned or not

**Comment by Ambryal** [comment]
Well brutes have never moved back after countering. But that's a good idea.

If the opponent can't move back because he is stunned, it is wise to make the other "move back".

I already added a slight knockback that's perfectly fine and will avoid some issues, i'll add a moveback but also keep a sleep of 150 as the moveback is 200 (and potentialy moveTo +200 right after or ability use) wich will let some time for the player to understand stun happened.

This will be in my end of the week PR.

**Pull request closed without merging**
